// Typical single serving in grams for the foods that show on /compare/ pages.
// Rough USDA household-measure values — enough for "1 breast vs 1 cup" framing.
// Foods not listed fall back to a 100 g / custom-grams control only.
export const SERVINGS: Record<string, { label: string; grams: number }> = {
  "chicken-breast": { label: "1 breast", grams: 120 },
  "chicken-thigh": { label: "1 thigh", grams: 90 },
  "ground-beef": { label: "1 patty", grams: 113 },
  "salmon": { label: "1 fillet", grams: 155 },
  "tuna": { label: "1 can, drained", grams: 142 },
  "shrimp": { label: "3 oz", grams: 85 },
  "cod": { label: "1 fillet", grams: 180 },
  "turkey-breast": { label: "2 slices", grams: 84 },
  "pork-chop": { label: "1 chop", grams: 145 },
  "bacon": { label: "2 slices", grams: 16 },
  "ham": { label: "2 slices", grams: 56 },
  "sausage": { label: "1 link", grams: 68 },
  "ground-turkey": { label: "3 oz", grams: 85 },
  "sardines": { label: "1 can, drained", grams: 92 },
  "tofu": { label: "1/2 cup", grams: 126 },
  "egg": { label: "1 large", grams: 50 },
  "milk": { label: "1 cup", grams: 244 },
  "skim-milk": { label: "1 cup", grams: 245 },
  "greek-yogurt": { label: "1 container", grams: 170 },
  "cheddar-cheese": { label: "1 slice", grams: 28 },
  "mozzarella": { label: "1 oz", grams: 28 },
  "cottage-cheese": { label: "1/2 cup", grams: 113 },
  "cream-cheese": { label: "2 tbsp", grams: 29 },
  "butter": { label: "1 tbsp", grams: 14 },
  "sour-cream": { label: "2 tbsp", grams: 30 },
  "white-rice": { label: "1 cup cooked", grams: 158 },
  "brown-rice": { label: "1 cup cooked", grams: 195 },
  "quinoa": { label: "1 cup cooked", grams: 185 },
  "oats": { label: "1/2 cup dry", grams: 40 },
  "pasta": { label: "1 cup cooked", grams: 140 },
  "whole-wheat-bread": { label: "1 slice", grams: 28 },
  "white-bread": { label: "1 slice", grams: 25 },
  "potato": { label: "1 medium", grams: 173 },
  "sweet-potato": { label: "1 medium", grams: 130 },
  "corn": { label: "1 ear / 1/2 cup", grams: 90 },
  "banana": { label: "1 medium", grams: 118 },
  "apple": { label: "1 medium", grams: 182 },
  "orange": { label: "1 medium", grams: 131 },
  "strawberries": { label: "1 cup", grams: 152 },
  "blueberries": { label: "1 cup", grams: 148 },
  "grapes": { label: "1 cup", grams: 151 },
  "mango": { label: "1 cup diced", grams: 165 },
  "pineapple": { label: "1 cup chunks", grams: 165 },
  "watermelon": { label: "1 cup diced", grams: 152 },
  "avocado": { label: "1/2 avocado", grams: 100 },
  "peach": { label: "1 medium", grams: 150 },
  "pear": { label: "1 medium", grams: 178 },
  "broccoli": { label: "1 cup", grams: 156 },
  "spinach": { label: "1 cup raw", grams: 30 },
  "kale": { label: "1 cup raw", grams: 21 },
  "carrot": { label: "1 medium", grams: 61 },
  "tomato": { label: "1 medium", grams: 123 },
  "cucumber": { label: "1/2 cucumber", grams: 150 },
  "onion": { label: "1/2 cup", grams: 80 },
  "bell-pepper": { label: "1 medium", grams: 119 },
  "mushrooms": { label: "1 cup", grams: 70 },
  "cauliflower": { label: "1 cup", grams: 107 },
  "green-peas": { label: "1/2 cup", grams: 80 },
  "zucchini": { label: "1 cup sliced", grams: 113 },
  "lettuce": { label: "1 cup shredded", grams: 47 },
  "black-beans": { label: "1/2 cup", grams: 86 },
  "chickpeas": { label: "1/2 cup", grams: 82 },
  "kidney-beans": { label: "1/2 cup", grams: 89 },
  "lentils": { label: "1/2 cup", grams: 99 },
  "edamame": { label: "1/2 cup", grams: 78 },
  "almonds": { label: "1 oz (23 nuts)", grams: 28 },
  "peanut-butter": { label: "2 tbsp", grams: 32 },
  "walnuts": { label: "1 oz", grams: 28 },
  "cashews": { label: "1 oz", grams: 28 },
  "olive-oil": { label: "1 tbsp", grams: 14 },
  "honey": { label: "1 tbsp", grams: 21 },
  "sugar": { label: "1 tsp", grams: 4 },
  "maple-syrup": { label: "1 tbsp", grams: 20 },
  "dark-chocolate": { label: "1 oz", grams: 28 },
  "roti": { label: "1 piece", grams: 40 },
  "naan": { label: "1 piece", grams: 90 },
  "dal-makhani": { label: "1 katori", grams: 150 },
  "butter-chicken": { label: "1 katori", grams: 150 },
  "palak-paneer": { label: "1 katori", grams: 150 },
  "vegetable-biryani": { label: "1 bowl", grams: 200 },
  "masala-dosa": { label: "1 dosa", grams: 150 },
  "idli": { label: "2 pieces", grams: 80 },
  "samosa": { label: "1 piece", grams: 60 },
  "poha": { label: "1 bowl", grams: 150 },
  "chicken-curry": { label: "1 katori", grams: 150 },
  "paratha": { label: "1 piece", grams: 80 },
  "plain-pulao": { label: "1 bowl", grams: 180 },
  "rajma": { label: "1 katori", grams: 150 },
  "khichdi": { label: "1 bowl", grams: 200 },
};
